# This pipeline builds the PDF ebook on any tag starting with 'v'.
name: "Create Release"
on:
  push:
    tags:
      - 'v*'

jobs:
  prepare-pdf:
    # Focal Fossa. Please don't use 'latest' tags, it's an anti-pattern.
    runs-on: ubuntu-20.04
    steps:
      # Checkout the code.
      - name: Checkout
        uses: actions/checkout@v2

      # Set a descriptive version. For PRs it'll be the short sha.
      - name: Set Version
        id: set_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # Prepare the content files.
      - name: Prepare Content
        run: ./scripts/prepare-markdown-for-ebook.sh ${{ steps.set_version.outputs.VERSION }}
      
      # Create a PDF from the prepared markdown.
      - name: Prepare PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: "-V toc-title:\"Table Of Contents\" --toc --pdf-engine=pdflatex --standalone --output hacker-laws.pdf hacker-laws.md"

      # Publish the PDF artifact.
      - name: Publish PDF Artifacts
        uses: actions/upload-artifact@master
        with:
          name: hacker-laws.pdf
          path: hacker-laws.pdf

  release:
    needs: prepare-pdf
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hacker-laws.pdf
          
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Hacker Laws E-Book
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./hacker-laws.pdf
          asset_name: hacker-laws.pdf
          asset_content_type: application/pdf
